name: raview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0

  provider:
  flutter_svg: 
  firebase_auth: ^5.5.2
  shared_preferences: ^2.5.3
  dartz:
  geolocator:
  geocoding:
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  intl:
  cloud_firestore: ^5.6.6
  rive:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/fonts/
    - assets/snackbar/
    - assets/snackbar/types/
    - assets/animated.riv
  
  fonts:
  -   family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300